### ISSUE TITLE
cannot start on Mac OS

### ISSUE THREAD

**Issue by t-cool** [tamamu/cl-exercise#4]
* (cl-exercise:start)

Hunchentoot server is started.
Listening on localhost:5000.
#S(CLACK.HANDLER::HANDLER
   :SERVER :HUNCHENTOOT
   :ACCEPTOR #<SB-THREAD:THREAD "clack-handler-hunchentoot" RUNNING
                {1003A05503}>)
* put[PUT] /eval/
....
[20:11:35] Connect in port 50000
[20:11:39] Method darkmatter/initialize
Params (trace NIL initializeOptions
        #<HASH-TABLE :TEST EQUAL :COUNT 4 {1001C8DCF3}>)
# ERROR: invalid number of arguments: 4

debugger invoked on a SB-KERNEL::ARG-COUNT-ERROR in thread
#<THREAD "hunchentoot-worker-127.0.0.1:58287" RUNNING {10044CCCD3}>:
  error while parsing arguments to DESTRUCTURING-BIND:
    too few elements in
      ()
    to satisfy lambda list
      (CLACK.HANDLER.HUNCHENTOOT::STATUS CLACK.HANDLER.HUNCHENTOOT::HEADERS
       &OPTIONAL (CLACK.HANDLER.HUNCHENTOOT::BODY)):
    between 2 and 3 expected, but got 0

**Comment by hiroki802** [comment]
After I installed proc-parse using ros install, it fixed.
? ros install fukamachi/proc-parse

**Comment by tamamu** [comment]
I added fukamachi/proc-parse to dependencies and installation, so it may solve this problem.
